version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - docker-network
  api:
    build: ./api
    restart: always
    environment:
      PORT: ${API_PORT}
      WEB_HOST: ${WEB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FRONT_PORT: ${FRONT_PORT}
      INTRA_ID: ${INTRA_ID}
      INTRA_SECRET: ${INTRA_SECRET}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - docker-network
    volumes:
      - ./api/:/usr/src/app/
      - /usr/src/app/node_modules
  frontend:
    build: ./frontend
    restart: always
    environment:
      REACT_APP_FRONT_PORT: ${FRONT_PORT}
      REACT_APP_WEB_HOST: ${WEB_HOST}
      REACT_APP_API_PORT: ${API_PORT}
      REACT_APP_INTRA_ID: ${INTRA_ID}
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    networks:
      - docker-network
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules
volumes:
  db:
    driver: local
networks:
  docker-network:
    driver: bridge
