version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - docker-network
  api:
    build: ./api
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - docker-network
    volumes:
      - ./api/:/usr/src/app/
volumes:
  db:
    driver: local
networks:
  docker-network:
    driver: bridge